### ISSUE TITLE
BUG: timeout not supported in Bordeaux Threads

### ISSUE THREAD

**Issue by mmontone** [robert-strandh/McCLIM#186]
In  Core/clim-basic/multiprocessing.lisp, :timeout parameter is passed to bt:condition-wait, but it is not supported (in my BordeauxThreads Quicklisp version at least). I'm running Linux.

It gets "fixed" if the :timeout argument is not passed.

```
modified   Core/clim-basic/multiprocessing.lisp
@@ -194,7 +194,7 @@ equivalent to progn."
   (bt:make-condition-variable))
 
 (defun condition-wait (cv lock &optional timeout)
-  (bt:condition-wait cv lock :timeout timeout))
+  (bt:condition-wait cv lock))
 
 (defun condition-notify (cv)
   (bt:condition-notify cv))
```

**Comment by dkochmanski** [comment]
What implementation do you use? afaik BT just maps into underlying implementation. For instance ECL doesn't have condition-wait with timeout.

Note, that if we use code with timeout on condition-wait, it is for a reason (if the reason is invalid, then we shouldn't provide this optional argument in `input.lisp` or in any place it is used). Therefore, I'm going to preserve usage of timeout argument if supplied, but omit it otherwise (like this):

```
modified   Core/clim-basic/multiprocessing.lisp
@@ -194,7 +194,12 @@ equivalent to progn."
   (bt:make-condition-variable))
 
 (defun condition-wait (cv lock &optional timeout)
-  (bt:condition-wait cv lock :timeout timeout))
+  ;; Some implementations have interface for condition wait with
+  ;; timeout, but raise an error when this function is called. When
+  ;; not necessary, we provide working variant.
+  (if timeout
+      (bt:condition-wait cv lock :timeout timeout)
+      (bt:condition-wait cv lock)))
 
 (defun condition-notify (cv)
   (bt:condition-notify cv))
```

hopefully it will fix your problems, but if not - please nag the CL implementation maintainer to implement the missing interface (in case of ECL, it will be me :).
