### ISSUE TITLE
Regression: draw-arrow broke between ql-dist 2017-10-19 and 2018-1 ql-dist

### ISSUE THREAD

**Issue by karlosz** [robert-strandh/McCLIM#426]
Draw-connector no longer functions. I had to revert to the October ql-dist to make it work.

**Comment by dkochmanski** [comment]
Hey, thanks for the report. Could you provide some more information? I don't know what are draw-connectors (neither do grep). It would be perfect if you could provide information about steps to reproduce, expected behavior and observed behavior.

**Comment by karlosz** [comment]
Okay, I narrowed it down between 2017-10-19 ql-dist and 2017-11-30 ql-dist.
The steps to reproduce are:
(In SBCL)
load this project:
https://github.com/karlosz/ir1-viewer

To use it, do something like (view (lambda (x) (tagbody :hi (print x) (go :hi)))).
In the October ql-dist, there are blue dotted arrows connecting the cblocks, which comes from the call to #'draw-connector. In the November dist, they vanish.

**Comment by karlosz** [comment]
Ach, I'm sorry, draw-connector is a function defined in that project. However, the regression still remains. The regression is with draw-arrow

**Comment by dkochmanski** [comment]
`(find-path start-point end-point step bounds limit-bound)` in `draw-connectors` always returns NIL (hence whole `awhen` block isn't evaluated). Function is hairy, but the problem is not `draw-arrow`. I can see there calls to `region-contains-region-p` and `region-intersects-region-p`.

If you could narrow it to a simple call which yields unexpected results that would be helpful.

**Comment by karlosz** [comment]
Commit db75def0595e66254a50f8d22a03471f5b2c53cd causes the regression
