### ISSUE TITLE
Gadgets not working with CLX-fb backend.

### ISSUE THREAD

**Issue by fittestbits** [robert-strandh/McCLIM#440]
Using McCLIM at
commit 23bef75d44b91c923b94d5aaa1404ed143630c74
Merge: 0d737417 e62edb00
Author: Nisar Ahmad <nisarahmad1324@gmail.com>
Date:   Sat Feb 3 23:16:34 2018 +0530
on SBCL and Fedora 27/fxce spin
```
(in-package :common-lisp-user)
(require :mcclim-clx-fb)
(setf clim:*default-server-path*  '(:clx-fb))
(require :clim-examples)
(clim-demo:run-demo 'gadget-test)
;; use pointer to operate the gadgets (sliders, check boxes, buttons, etc) - they don't work for me
```
gadget-test does work for me with CLX instead of CLX-fb

**Comment by dkochmanski** [comment]
bug confirmed.

**Comment by dkochmanski** [comment]
bisection revealed that responsible commit is: e62edb00e8833e8436abc5ec8c5db1e02ac3d875 (suprise suprise, the one which "fixes" distribute event). It seems that the problem is not general distribute-event method (specialized on `pointer-event`) but rather distribute-enter/exit-events. Investiagting.
