### ISSUE TITLE
pointer-position not adhere to spec

### ISSUE THREAD

**Issue by admich** [robert-strandh/McCLIM#466]
In the spec is written (in a annotation) tha pointer-position function return the coordinates relative to the graft, but mcclim clx implementation return the coordinates respect to the pointer sheet as written in the franz clim manual. What is the correct specifications?

pointer-position have also the problem that return nil if there is not pointer sheet and an error if pointer sheet is not more mirrored #465

**Comment by nsrahmad** [comment]
Annotations on the spec are not part of the spec, Those are just comments added by CLIM hackers which provide some insight, or clear confusion. That said McCLIM follows the Specifications first, if something is not clear or undefined, in that case Franz CLIM manual is referenced.

In this particular case, Spec does not say anything about coordinate system used.

Since  CLX already have [`pointer-position`](http://bauhh.de/clxman/12_6_Pointer_Position.html#pointer-position) which provides `pointer-position` relative to window coordinates (Other GUI toolkits follow this convention), it seems the right choice.
