### ISSUE TITLE
stream-pointer-position wrong coordinates

### ISSUE THREAD

**Issue by admich** [robert-strandh/McCLIM#467]
The stream-pointer-position function returns the coordinates of the pointer in the pointer's sheet coordinate system not in the coordinates of the stream argument coordinate systems.

**Comment by admich** [comment]
I try to solve the problem with this:
https://github.com/admich/McCLIM/commit/2a7af9843cce64ba480a85210f838b2974a9ea6d
It seems to work and it solves also issue #465 because with this code `stream-position-code` does not call `pointer-position` that I think is buggy (issue #466).

**Comment by nsrahmad** [comment]
Hello @admich , Your changes looks reasonable (I haven't tried them yet). In order to test and merge it in McCLIM, I need you to open a Pull Request. You had contributed before with this patch-included style (e.g #293) , but anything non-trivial is much easier with [GIthub's work flow](https://guides.github.com/introduction/flow/).
